"""
Food Nutrition Knowledge Base & Ground Truth Calibrations
Based on USDA FoodData Central standards for standard portion sizes.
"""

FOOD_DATABASE = {
    "grilled_chicken_rice_bowl": {
        "name": "Grilled Chicken Rice Bowl",
        "category": "Main Course",
        "calories": 650.0,
        "protein": 38.0,
        "carbohydrates": 72.0,
        "fat": 19.0,
        "fiber": 5.2,
        "sugar": 3.8,
        "sodium": 580.0,
        "potassium": 640.0,
        "servingSize": "1 bowl (approx. 420g)",
        "healthRating": "High Protein & Balanced",
        "dietaryTags": ["High Protein", "Low Sugar", "Lean Meat"],
        "ingredients": ["Grilled Chicken Breast", "Brown/Jasmine Rice", "Steamed Broccoli", "Carrots", "Sesame Oil", "Light Soy Sauce"],
        "healthTips": "Excellent lean protein source combined with complex carbohydrates. Perfect for muscle recovery and sustained energy.",
        "sampleImage": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80"
    },
    "chicken_biryani": {
        "name": "Chicken Biryani",
        "category": "Main Course",
        "calories": 720.0,
        "protein": 34.0,
        "carbohydrates": 84.0,
        "fat": 26.0,
        "fiber": 4.1,
        "sugar": 2.5,
        "sodium": 780.0,
        "potassium": 510.0,
        "servingSize": "1 plate (approx. 450g)",
        "healthRating": "Calorie Dense & Rich in Protein",
        "dietaryTags": ["High Protein", "Gluten-Free", "Aromatic Spices"],
        "ingredients": ["Basmati Rice", "Chicken", "Yogurt", "Ghee / Oil", "Fried Onions", "Saffron", "Cardamom & Cloves"],
        "healthTips": "Rich in spices like turmeric and saffron with natural anti-inflammatory benefits. Pair with cucumber raita to aid digestion.",
        "sampleImage": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80"
    },
    "masala_dosa": {
        "name": "Masala Dosa",
        "category": "Breakfast / Light Meal",
        "calories": 420.0,
        "protein": 11.5,
        "carbohydrates": 64.0,
        "fat": 14.0,
        "fiber": 4.8,
        "sugar": 2.0,
        "sodium": 620.0,
        "potassium": 380.0,
        "servingSize": "1 piece with potato filling (approx. 220g)",
        "healthRating": "Moderate Calorie / Carb Source",
        "dietaryTags": ["Vegetarian", "Fermented", "Gut Healthy"],
        "ingredients": ["Fermented Rice-Lentil Batter", "Potato Masala", "Mustard Seeds", "Curry Leaves", "Coconut Chutney", "Sambar"],
        "healthTips": "Naturally fermented batter promotes a healthy gut microbiome. Enjoy with protein-rich lentil sambar for a balanced macro profile.",
        "sampleImage": "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80"
    },
    "paneer_butter_masala": {
        "name": "Paneer Butter Masala",
        "category": "Main Course",
        "calories": 560.0,
        "protein": 21.0,
        "carbohydrates": 26.0,
        "fat": 42.0,
        "fiber": 3.6,
        "sugar": 7.2,
        "sodium": 690.0,
        "potassium": 430.0,
        "servingSize": "1 cup serving (approx. 280g)",
        "healthRating": "High Calcium & Vegetarian Protein",
        "dietaryTags": ["Vegetarian", "Keto Friendly", "High Calcium"],
        "ingredients": ["Cottage Cheese (Paneer)", "Tomato Puree", "Butter & Fresh Cream", "Cashew Paste", "Garam Masala", "Fenugreek Leaves"],
        "healthTips": "Rich in bioavailable calcium and caseinated protein. Consider pairing with whole wheat roti rather than refined naan.",
        "sampleImage": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80"
    },
    "salmon_quinoa_bowl": {
        "name": "Salmon Quinoa Power Bowl",
        "category": "Main Course",
        "calories": 580.0,
        "protein": 42.0,
        "carbohydrates": 48.0,
        "fat": 22.0,
        "fiber": 6.8,
        "sugar": 3.1,
        "sodium": 440.0,
        "potassium": 890.0,
        "servingSize": "1 bowl (approx. 380g)",
        "healthRating": "Superfood & Omega-3 Rich",
        "dietaryTags": ["Heart Healthy", "High Omega-3", "Gluten-Free", "High Protein"],
        "ingredients": ["Atlantic Salmon Fillet", "Cooked Tricolor Quinoa", "Avocado", "Baby Spinach", "Edamame", "Lemon Vinaigrette"],
        "healthTips": "Outstanding source of EPA/DHA Omega-3 fatty acids for cardiovascular and brain health. Complete amino acid profile from quinoa.",
        "sampleImage": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80"
    },
    "avocado_toast": {
        "name": "Avocado Egg Sourdough Toast",
        "category": "Breakfast",
        "calories": 410.0,
        "protein": 16.0,
        "carbohydrates": 38.0,
        "fat": 23.0,
        "fiber": 8.5,
        "sugar": 1.8,
        "sodium": 390.0,
        "potassium": 620.0,
        "servingSize": "2 slices (approx. 240g)",
        "healthRating": "Healthy Fats & Fiber Rich",
        "dietaryTags": ["Vegetarian", "Heart Healthy", "High Fiber"],
        "ingredients": ["Whole Grain Sourdough", "Fresh Hass Avocado", "Poached Egg", "Hemp Seeds", "Chili Flakes", "Extra Virgin Olive Oil"],
        "healthTips": "Monounsaturated fats from avocado support optimal HDL cholesterol levels while high dietary fiber supports gut health.",
        "sampleImage": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80"
    },
    "caesar_salad": {
        "name": "Classic Chicken Caesar Salad",
        "category": "Salad / Starter",
        "calories": 460.0,
        "protein": 32.0,
        "carbohydrates": 18.0,
        "fat": 29.0,
        "fiber": 3.8,
        "sugar": 2.4,
        "sodium": 740.0,
        "potassium": 470.0,
        "servingSize": "1 bowl (approx. 320g)",
        "healthRating": "High Protein / Low Carb",
        "dietaryTags": ["Low Carb", "Keto Friendly", "High Protein"],
        "ingredients": ["Crisp Romaine Lettuce", "Grilled Chicken Breast", "Shaved Parmesan", "Garlic Herb Croutons", "Classic Caesar Dressing"],
        "healthTips": "High in leafy green vitamins (A, K, folate). For a lighter dressing, ask for dressing on the side or replace with Greek yogurt caesar.",
        "sampleImage": "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80"
    },
    "pepperoni_pizza": {
        "name": "Artisan Pepperoni Pizza",
        "category": "Fast Food / Cheat Meal",
        "calories": 780.0,
        "protein": 33.0,
        "carbohydrates": 82.0,
        "fat": 36.0,
        "fiber": 3.5,
        "sugar": 6.5,
        "sodium": 1250.0,
        "potassium": 380.0,
        "servingSize": "2 large slices (approx. 260g)",
        "healthRating": "High Calorie / High Sodium",
        "dietaryTags": ["Cheat Meal", "Comfort Food"],
        "ingredients": ["Fermented Pizza Dough", "San Marzano Tomato Sauce", "Whole Milk Mozzarella", "Cured Pepperoni", "Oregano"],
        "healthTips": "High in sodium and saturated fats. Balance with a fresh green side salad to increase fiber intake and manage glycemic spike.",
        "sampleImage": "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=800&q=80"
    },
    "oatmeal_berry_bowl": {
        "name": "Overnight Berry Oatmeal Bowl",
        "category": "Breakfast",
        "calories": 360.0,
        "protein": 14.0,
        "carbohydrates": 62.0,
        "fat": 7.0,
        "fiber": 9.2,
        "sugar": 14.0,
        "sodium": 110.0,
        "potassium": 460.0,
        "servingSize": "1 bowl (approx. 300g)",
        "healthRating": "High Fiber & Antioxidant Rich",
        "dietaryTags": ["Vegetarian", "Heart Healthy", "High Fiber", "Low Sodium"],
        "ingredients": ["Rolled Oats", "Almond Milk", "Blueberries & Strawberries", "Chia Seeds", "Honey", "Crushed Walnuts"],
        "healthTips": "Beta-glucan soluble fiber in oats actively helps lower LDL cholesterol. Antioxidant flavonoids protect against oxidative stress.",
        "sampleImage": "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=800&q=80"
    },
    "greek_salad": {
        "name": "Mediterranean Greek Salad",
        "category": "Salad / Starter",
        "calories": 320.0,
        "protein": 9.0,
        "carbohydrates": 16.0,
        "fat": 25.0,
        "fiber": 4.5,
        "sugar": 5.5,
        "sodium": 590.0,
        "potassium": 520.0,
        "servingSize": "1 large plate (approx. 290g)",
        "healthRating": "Low Calorie & Antioxidant Packed",
        "dietaryTags": ["Vegetarian", "Mediterranean Diet", "Low Carb"],
        "ingredients": ["Kalamata Olives", "Feta Cheese", "Cucumbers", "Cherry Tomatoes", "Red Onions", "Extra Virgin Olive Oil", "Oregano"],
        "healthTips": "Core Mediterranean staple loaded with polyphenols, vitamin C, and healthy monounsaturated fatty acids.",
        "sampleImage": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80"
    }
}
